export enum CurrencyField {
  SWAP_INPUT = 'SWAP_INPUT',
  SWAP_OUTPUT = 'SWAP_OUTPUT',
  ADD_LIQUIDITY_CURRENCY0 = 'ADD_LIQUIDITY_CURRENCY0',
  ADD_LIQUIDITY_CURRENCY1 = 'ADD_LIQUIDITY_CURRENCY1',
  REMOVE_LIQUIDITY_CURRENCY0 = 'REMOVE_LIQUIDITY_CURRENCY0',
  REMOVE_LIQUIDITY_CURRENCY1 = 'REMOVE_LIQUIDITY_CURRENCY1',
}
