export enum CrossChainOrderStatus {
  ORDER_SUBMITTED = 'ORDER_SUBMITTED',
  ORDER_PARTIAL_SUCCESS = 'ORDER_PARTIAL_SUCCESS',
  ORDER_SUCCESS = 'ORDER_SUCCESS',
  ORDER_FAILED = 'ORDER_FAILED',
}

export enum CrossChainOrderStepType {
  SWAP_AT_SOURCE_CHAIN = 'SWAP_AT_SOURCE_CHAIN',
  BRIDGE = 'BRIDGE',
  SWAP_AT_DESTINATION_CHAIN = 'SWAP_AT_DESTINATION_CHAIN',
}

export enum CrossChainOrderStepStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  PARTIAL_SUCCESS = 'PARTIAL_SUCCESS',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}
