name: Sync Upstream

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/6 * * *' # every 6 hours

jobs:
  sync_upstream:
    name: Sync latest commits from Upstream
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Sync Upstream
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: pancakeswap/frontend-private
          upstream_sync_branch: feature/v4-liquidity
          target_sync_branch: feature/v4-preview
          git_config_pull_rebase: true
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false
          target_branch_push_args: '--force'
